//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cineAppNCapas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCESOPREMIER
    {
        public int idPremier { get; set; }
        public string nombrePelicula { get; set; }
        public Nullable<int> idPersona { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
        public virtual PELICULA PELICULA { get; set; }
    }
}
