//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cineAppNCapas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PELICULA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PELICULA()
        {
            this.ACCESOPREMIER = new HashSet<ACCESOPREMIER>();
        }
    
        public string nombre { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan duracion { get; set; }
        public string clasificacion { get; set; }
        public string estudio { get; set; }
        public string director { get; set; }
        public string genero { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCESOPREMIER> ACCESOPREMIER { get; set; }
    }
}
